### ISSUE TITLE
你好，在微信付款过程中如果客户端取消付款如何返回相关页面？

### ISSUE THREAD

**Issue by uchqur** [xhat/payjs-laravel#4]
你好，在微信付款过程中如果客户端取消付款如何返回相关页面？
因为客户端付款过程中不付款就会直接退出浏览器返回微信了，有没有办法扑住这过程？
谢谢

**Comment by xhat** [comment]
可以。
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6
